# Data and Vocabulary Settings
# These will be updated by the data pipeline
src_vocab_size: 5000 # Placeholder
tgt_vocab_size: 5000 # Placeholder

# Model Hyperparameters (Laptop-Friendly)
d_model: 128
num_layers: 2
num_heads: 4
d_ff: 256
dropout: 0.1
max_seq_len: 100

# Training Hyperparameters
batch_size: 8
learning_rate: 0.0001
num_epochs: 5